name: Generate 1-Month Key
on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Admin Password'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    if: github.event.inputs.password == ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Key
        run: |
          # Generates a key like ABCD-1234-EFGH-5678
          NEW_KEY=$(openssl rand -hex 8 | tr '[:lower:]' '[:upper:]' | sed 's/.\{4\}/&-/g;s/-$//')
          # Append to the JSON array
          jq ". += [{\"key\": \"$NEW_KEY\", \"duration\": \"1 Month\", \"status\": \"ACTIVE\"}]" keys.json > temp.json && mv temp.json keys.json
      - name: Commit Change
        run: |
          git config --global user.name "KeyGen-Bot"
          git config --global user.email "bot@github.com"
          git add keys.json
          git commit -m "Generated new 1-month key"
          git push
